version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: app-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: spa/Dockerfile.prod
    container_name: app-frontend
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: spa/Dockerfile.prod
    ports:
      - "3000:80"
      - "8000:8000"
    volumes:
      - ./api/public:/var/www/public
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: docker-project
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3317:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
