version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: mg-prod-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - mg-prod-network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile.prod
    container_name: mg-prod-frontend
    restart: unless-stopped
    ports:
      - "3802:80"
    depends_on:
      - backend
    networks:
      - mg-prod-network

  mysql:
    image: mysql:8.0
    container_name: mg-prod-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e-navbatchi
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3317:3306"
    networks:
      - mg-prod-network

networks:
  mg-prod-network:
    driver: bridge
