version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: mg_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - mg_network

  nginx:
    image: nginx:alpine
    container_name: mg_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mg_network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile.prod
    container_name: mg_frontend
    restart: unless-stopped
    ports:
      - "3802:80"
    depends_on:
      - backend
    networks:
      - mg_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e-navbatchi
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3317:3306"
    networks:
      - mg_network

networks:
  mg_network:
    driver: bridge
