services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mg_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    ports:
      - "8082:8082"
    networks:
      - mg_network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile
    container_name: mg_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./spa:/app
    environment:
      - NODE_ENV=production
    ports:
      - "3078:3078"
      - "6006:6006"
    networks:
      - mg_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-navbatchi
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
    ports:
      - "3317:3308"
    volumes:
      - e-navbatchi-mysql:/var/lib/mysql
    networks:
      - mg_network

networks:
  mg_network:
    driver: bridge

volumes:
  e-navbatchi-mysql:
