version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: mg_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    environment:
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=e-navbatchi
      - DB_USERNAME=root
      - DB_PASSWORD=1111
    expose:
      - "9000"
    depends_on:
      - mysql
    networks:
      - mg_network

  nginx:
    image: nginx:alpine
    container_name: mg_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mg_network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile
    container_name: mg_frontend
    restart: unless-stopped
    ports:
      - "3802:80"
    volumes:
      - ./spa:/app # Монтируем папку spa внутрь контейнера
    depends_on:
      - backend
    networks:
      - mg_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e-navbatchi
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3317:3306"
    volumes:
      - e-navbatchi-mysql:/var/lib/mysql
    networks:
      - mg_network

networks:
  mg_network:
    driver: bridge

volumes:
  e-navbatchi-mysql:
