version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: mg_backend
    restart: unless-stopped
    working_dir: /mg/api
    volumes:
      - ./api:/mg/api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - mg_network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile.dev
    tty: true
    container_name: mg_frontend
    restart: unless-stopped
    working_dir: /mg/spa
    volumes:
      - ./spa:/mg/spa
    ports:
      - "3030:3030"
    depends_on:
      - backend
    networks:
      - mg_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e-navbatchi
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3317:3306"
    networks:
      - mg_network

networks:
  mg_network:
    driver: bridge
