version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: Myapp_backend
    restart: unless-stopped
    working_dir: /Myapp/api
    volumes:
      - ./api:/Myapp/api
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - mysql
    networks:
      - Myapp_network

  frontend:
    build:
      context: ./spa
      dockerfile: Dockerfile.dev
    tty: true
    container_name: Myapp_frontend
    restart: unless-stopped
    working_dir: /Myapp/spa
    volumes:
      - ./spa:/Myapp/spa
    ports:
      - "${FRONTEND_PORT}:3030"
    depends_on:
      - backend
    networks:
      - Myapp_network

  mysql:
    image: mysql:8.0
    container_name: Myapp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Myapp
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - Myapp_network

networks:
  Myapp_network:
    driver: bridge
