FROM node:18-alpine AS build-stage

WORKDIR /app

COPY spa/package.json spa/package-lock.json ./
RUN npm install

COPY spa .
RUN npm run build


FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
